//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Core.App_GlobalResources.Orientation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceOrientation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceOrientation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMS.Core.App_GlobalResources.Orientation.ResourceOrientation", typeof(ResourceOrientation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ft_lbl_FullName {
            get {
                return ResourceManager.GetString("ft_lbl_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation Standard.
        /// </summary>
        public static string ft_lbl_JobTitle {
            get {
                return ResourceManager.GetString("ft_lbl_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EID.
        /// </summary>
        public static string ft_lbl_TraineeCode {
            get {
                return ResourceManager.GetString("ft_lbl_TraineeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EID.
        /// </summary>
        public static string lbl_EID {
            get {
                return ResourceManager.GetString("lbl_EID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string lbl_Filter {
            get {
                return ResourceManager.GetString("lbl_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lbl_Home {
            get {
                return ResourceManager.GetString("lbl_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Potential Successor.
        /// </summary>
        public static string lbl_InformationPotentialSuccessor {
            get {
                return ResourceManager.GetString("lbl_InformationPotentialSuccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassPort No.
        /// </summary>
        public static string lbl_Passport {
            get {
                return ResourceManager.GetString("lbl_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDP List.
        /// </summary>
        public static string lbl_PDPList {
            get {
                return ResourceManager.GetString("lbl_PDPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Development Planning.
        /// </summary>
        public static string lbl_PDPManagement {
            get {
                return ResourceManager.GetString("lbl_PDPManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string tb_lbl_FullName {
            get {
                return ResourceManager.GetString("tb_lbl_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Occupation Standard.
        /// </summary>
        public static string tb_lbl_JobTitle {
            get {
                return ResourceManager.GetString("tb_lbl_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string tb_lbl_Position {
            get {
                return ResourceManager.GetString("tb_lbl_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EID.
        /// </summary>
        public static string tb_lbl_TraineeCode {
            get {
                return ResourceManager.GetString("tb_lbl_TraineeCode", resourceCulture);
            }
        }
    }
}
