//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CONTRACTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_CONTRACTOR()
        {
            this.TMS_CONTRACTS = new HashSet<TMS_CONTRACTS>();
        }
    
        public int id { get; set; }
        public string str_Code { get; set; }
        public string str_Sortname { get; set; }
        public string str_Fullname { get; set; }
        public string str_Description { get; set; }
        public Nullable<System.DateTime> dtm_Created_date { get; set; }
        public Nullable<int> int_Created_by { get; set; }
        public Nullable<bool> bit_Isactive { get; set; }
        public Nullable<System.DateTime> dtm_Updated_date { get; set; }
        public Nullable<int> int_Updated_by { get; set; }
        public string str_address { get; set; }
        public string str_masothue { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_CONTRACTS> TMS_CONTRACTS { get; set; }
    }
}
