//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG
    {
        public int ID { get; set; }
        public Nullable<bool> NOT_ON_OFF { get; set; }
        public string KEY { get; set; }
        public string VALUE { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public bool isExtension { get; set; }
    }
}
