//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Blended_Learning
    {
        public int Id { get; set; }
        public Nullable<int> Course_Detail_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string LearningType { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string TimeFrom { get; set; }
        public string TimeTo { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<int> ExaminerId { get; set; }
        public Nullable<int> mark_type_cro { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<decimal> Allowance { get; set; }
    
        public virtual Course_Detail Course_Detail { get; set; }
        public virtual Room Room { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
