//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Attendance
    {
        public int Id { get; set; }
        public Nullable<int> CourseDetailId { get; set; }
        public Nullable<int> TraineeId { get; set; }
        public Nullable<int> Type { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> AttendedDate { get; set; }
        public Nullable<int> Attender { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreaatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Course_Detail Course_Detail { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual USER USER { get; set; }
    }
}
