//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Detail_Instructor
    {
        public int Id { get; set; }
        public Nullable<int> Course_Detail_Id { get; set; }
        public Nullable<int> Instructor_Id { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Course_Detail Course_Detail { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
