//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Detail_Course_Ingredients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_Detail_Course_Ingredients()
        {
            this.Course_Result_Course_Detail_Ingredient = new HashSet<Course_Result_Course_Detail_Ingredient>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CourseDetailId { get; set; }
        public Nullable<int> CourseIngredientId { get; set; }
        public Nullable<int> Percent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Course_Detail Course_Detail { get; set; }
        public virtual Course_Ingredients_Learning Course_Ingredients_Learning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Result_Course_Detail_Ingredient> Course_Result_Course_Detail_Ingredient { get; set; }
    }
}
