//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_TrainingCenter
    {
        public int id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> khoidaotao_id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
    }
}
