//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Detail_Score
    {
        public int Id { get; set; }
        public Nullable<int> CourseDetailId { get; set; }
        public Nullable<double> Score { get; set; }
        public string Grade { get; set; }
    
        public virtual Course_Detail Course_Detail { get; set; }
    }
}
