//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRemarkCheckFail
    {
        public int Id { get; set; }
        public Nullable<int> CourseResultID { get; set; }
        public string RemarkContent { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> InstructorId { get; set; }
    
        public virtual Course_Result Course_Result { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
