//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Certificate_Subjects
    {
        public int Id { get; set; }
        public Nullable<int> IdGroupCertificate { get; set; }
        public Nullable<int> IdSubject { get; set; }
    
        public virtual Group_Certificate Group_Certificate { get; set; }
    }
}
