//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group_Roles()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string str_Group_Name { get; set; }
        public Nullable<bool> bit_UserProfile { get; set; }
        public Nullable<bool> bit_Department { get; set; }
        public Nullable<bool> bit_Subject { get; set; }
        public Nullable<bool> bit_JobTitle { get; set; }
        public Nullable<bool> bit_Room { get; set; }
        public Nullable<bool> bit_Course { get; set; }
        public Nullable<bool> bit_Trainee { get; set; }
        public Nullable<bool> bit_Group { get; set; }
        public Nullable<bool> bit_Report { get; set; }
        public Nullable<bool> bit_Configuration { get; set; }
        public Nullable<bool> bit_RegisterTrainee { get; set; }
        public Nullable<bool> bit_Approve { get; set; }
        public Nullable<bool> bit_Instructor { get; set; }
        public Nullable<bool> bit_Recurrent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
