//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupUserMenu
    {
        public int Id { get; set; }
        public Nullable<int> GroupUserId { get; set; }
        public Nullable<int> GroupFunctionId { get; set; }
        public Nullable<int> FunctionType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual GroupFunction GroupFunction { get; set; }
        public virtual GroupUser GroupUser { get; set; }
    }
}
