//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Certificate_Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group_Certificate_Schedule()
        {
            this.Group_Certificate_Schedule_Detail = new HashSet<Group_Certificate_Schedule_Detail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdGroupCertificate { get; set; }
        public Nullable<int> IdTrainee { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Date_Of_Issue { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public string SRNO { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Path { get; set; }
    
        public virtual Group_Certificate Group_Certificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_Certificate_Schedule_Detail> Group_Certificate_Schedule_Detail { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
