//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Certificate_Schedule_Detail
    {
        public int IdScheduleGroupCertificate { get; set; }
        public int IdSubject { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Group_Certificate_Schedule Group_Certificate_Schedule { get; set; }
        public virtual SubjectDetail SubjectDetail { get; set; }
    }
}
