//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGECONFIG
    {
        public int ID { get; set; }
        public string KEY { get; set; }
        public Nullable<int> WIDTH { get; set; }
        public Nullable<int> HEIGHT { get; set; }
        public Nullable<bool> ISRATIO { get; set; }
        public string MODULE { get; set; }
    }
}
