//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Tiltle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job_Tiltle()
        {
            this.Courses = new HashSet<Course>();
            this.Title_Standard = new HashSet<Title_Standard>();
            this.Trainees = new HashSet<Trainee>();
        }
    
        public int Job_Title_Id { get; set; }
        public string str_Name { get; set; }
        public bool bit_Deleted { get; set; }
        public string str_Created_By { get; set; }
        public string str_Deleted_By { get; set; }
        public string str_Last_Modified_By { get; set; }
        public Nullable<System.DateTime> dtm_Created_At { get; set; }
        public Nullable<System.DateTime> dtm_Deleted_At { get; set; }
        public Nullable<System.DateTime> dtm_Last_Modified_At { get; set; }
        public string str_Code { get; set; }
        public string str_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Title_Standard> Title_Standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainee> Trainees { get; set; }
    }
}
