//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_Expiredate
    {
        public int id { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
        public string certificate { get; set; }
        public string backgroundcertificate { get; set; }
        public Nullable<int> type_certificate { get; set; }
        public Nullable<int> statuscertificate { get; set; }
        public Nullable<int> lmsstatus { get; set; }
        public string issue_name { get; set; }
        public Nullable<int> course_result_id { get; set; }
    
        public virtual Course_Result Course_Result { get; set; }
    }
}
