//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_Assign
    {
        public int Id { get; set; }
        public Nullable<int> TraineeId { get; set; }
        public Nullable<int> CourseDetailId { get; set; }
        public Nullable<int> Status { get; set; }
        public string AssignBy { get; set; }
        public string ApproveBy { get; set; }
    }
}
