//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_REQUEST
    {
        public int id { get; set; }
        public Nullable<int> id_item { get; set; }
        public string type_request { get; set; }
        public string result { get; set; }
        public string messege { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
