//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Management_Room_Item
    {
        public int Id { get; set; }
        public Nullable<int> IdManagementRoom { get; set; }
        public Nullable<int> IdRoom { get; set; }
        public Nullable<System.DateTime> dtm_time_from { get; set; }
        public Nullable<System.DateTime> dtm_time_to { get; set; }
        public string time_from { get; set; }
        public string time_to { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Management_Room Management_Room { get; set; }
        public virtual Room Room { get; set; }
    }
}
