//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EFDbContext : DbContext
    {
        public EFDbContext()
            : base("name=EFDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Approve_Status> Approve_Status { get; set; }
        public virtual DbSet<AspNet_SqlCacheTablesForChangeNotification> AspNet_SqlCacheTablesForChangeNotification { get; set; }
        public virtual DbSet<ASPStateTempApplication> ASPStateTempApplications { get; set; }
        public virtual DbSet<ASPStateTempSession> ASPStateTempSessions { get; set; }
        public virtual DbSet<CallApproveService> CallApproveServices { get; set; }
        public virtual DbSet<CAT_CERTIFICATE> CAT_CERTIFICATE { get; set; }
        public virtual DbSet<CAT_CERTIFICATE_ITEM> CAT_CERTIFICATE_ITEM { get; set; }
        public virtual DbSet<CAT_CONTRACTOR> CAT_CONTRACTOR { get; set; }
        public virtual DbSet<CAT_CONTRACTS_STATUS> CAT_CONTRACTS_STATUS { get; set; }
        public virtual DbSet<CAT_CONTRACTS_TYPE> CAT_CONTRACTS_TYPE { get; set; }
        public virtual DbSet<CAT_COSTS> CAT_COSTS { get; set; }
        public virtual DbSet<CAT_GROUPCOST> CAT_GROUPCOST { get; set; }
        public virtual DbSet<CAT_GROUPSUBJECT> CAT_GROUPSUBJECT { get; set; }
        public virtual DbSet<CAT_GROUPSUBJECT_ITEM> CAT_GROUPSUBJECT_ITEM { get; set; }
        public virtual DbSet<CAT_MAIL> CAT_MAIL { get; set; }
        public virtual DbSet<CAT_MAIL_KEY> CAT_MAIL_KEY { get; set; }
        public virtual DbSet<CAT_NATIONALITY> CAT_NATIONALITY { get; set; }
        public virtual DbSet<CAT_PARTNER> CAT_PARTNER { get; set; }
        public virtual DbSet<CAT_PROVINCES> CAT_PROVINCES { get; set; }
        public virtual DbSet<CAT_UNITS> CAT_UNITS { get; set; }
        public virtual DbSet<CAT_USER_GENDER> CAT_USER_GENDER { get; set; }
        public virtual DbSet<CAT_USER_TYPE> CAT_USER_TYPE { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CONFIG> CONFIGs { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Course_Attendance> Course_Attendance { get; set; }
        public virtual DbSet<Course_Blended_Learning> Course_Blended_Learning { get; set; }
        public virtual DbSet<Course_Cost> Course_Cost { get; set; }
        public virtual DbSet<Course_Detail> Course_Detail { get; set; }
        public virtual DbSet<Course_Detail_Course_Ingredients> Course_Detail_Course_Ingredients { get; set; }
        public virtual DbSet<Course_Detail_Instructor> Course_Detail_Instructor { get; set; }
        public virtual DbSet<Course_Detail_Room> Course_Detail_Room { get; set; }
        public virtual DbSet<Course_Detail_Room_Global> Course_Detail_Room_Global { get; set; }
        public virtual DbSet<Course_Detail_Score> Course_Detail_Score { get; set; }
        public virtual DbSet<Course_Detail_Subject_Note> Course_Detail_Subject_Note { get; set; }
        public virtual DbSet<Course_Ingredients_Learning> Course_Ingredients_Learning { get; set; }
        public virtual DbSet<Course_LMS_STATUS> Course_LMS_STATUS { get; set; }
        public virtual DbSet<Course_Result> Course_Result { get; set; }
        public virtual DbSet<Course_Result_Course_Detail_Ingredient> Course_Result_Course_Detail_Ingredient { get; set; }
        public virtual DbSet<Course_Result_Final> Course_Result_Final { get; set; }
        public virtual DbSet<Course_Result_Summary> Course_Result_Summary { get; set; }
        public virtual DbSet<Course_Result_Temp> Course_Result_Temp { get; set; }
        public virtual DbSet<Course_Subject_Item> Course_Subject_Item { get; set; }
        public virtual DbSet<Course_TrainingCenter> Course_TrainingCenter { get; set; }
        public virtual DbSet<Course_Type> Course_Type { get; set; }
        public virtual DbSet<Course_Type_Result> Course_Type_Result { get; set; }
        public virtual DbSet<CourseRemarkCheckFail> CourseRemarkCheckFails { get; set; }
        public virtual DbSet<CourseRemarkCheckFail_LMS> CourseRemarkCheckFail_LMS { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Examiner_Ability> Examiner_Ability { get; set; }
        public virtual DbSet<Examiner_Ability_LOG> Examiner_Ability_LOG { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Group_Certificate> Group_Certificate { get; set; }
        public virtual DbSet<Group_Certificate_Schedule> Group_Certificate_Schedule { get; set; }
        public virtual DbSet<Group_Certificate_Schedule_Detail> Group_Certificate_Schedule_Detail { get; set; }
        public virtual DbSet<Group_Certificate_Subjects> Group_Certificate_Subjects { get; set; }
        public virtual DbSet<Group_Roles> Group_Roles { get; set; }
        public virtual DbSet<GroupFunction> GroupFunctions { get; set; }
        public virtual DbSet<GroupPermissionFunction> GroupPermissionFunctions { get; set; }
        public virtual DbSet<GroupTrainee> GroupTrainees { get; set; }
        public virtual DbSet<GroupTrainee_Item> GroupTrainee_Item { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<GroupUserAccess> GroupUserAccesses { get; set; }
        public virtual DbSet<GroupUserMenu> GroupUserMenus { get; set; }
        public virtual DbSet<GroupUserPermission> GroupUserPermissions { get; set; }
        public virtual DbSet<IMAGECONFIG> IMAGECONFIGs { get; set; }
        public virtual DbSet<INFO_CONTACT> INFO_CONTACT { get; set; }
        public virtual DbSet<INFO_REPLY_CONTACT> INFO_REPLY_CONTACT { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Instructor_Ability> Instructor_Ability { get; set; }
        public virtual DbSet<Instructor_Ability_LOG> Instructor_Ability_LOG { get; set; }
        public virtual DbSet<JobTitle> JobTitles { get; set; }
        public virtual DbSet<JobtitleHeader> JobtitleHeaders { get; set; }
        public virtual DbSet<JobtitleLevel> JobtitleLevels { get; set; }
        public virtual DbSet<JobtitlePosition> JobtitlePositions { get; set; }
        public virtual DbSet<LMS_Assign> LMS_Assign { get; set; }
        public virtual DbSet<LMS_Expiredate> LMS_Expiredate { get; set; }
        public virtual DbSet<LMS_REQUEST> LMS_REQUEST { get; set; }
        public virtual DbSet<Management_Room> Management_Room { get; set; }
        public virtual DbSet<Management_Room_Item> Management_Room_Item { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<Meeting_Participants> Meeting_Participants { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<MenuName> MenuNames { get; set; }
        public virtual DbSet<Monitor_Ability> Monitor_Ability { get; set; }
        public virtual DbSet<Monitor_Ability_LOG> Monitor_Ability_LOG { get; set; }
        public virtual DbSet<Nation> Nations { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Notification_Detail> Notification_Detail { get; set; }
        public virtual DbSet<Orientation> Orientations { get; set; }
        public virtual DbSet<Orientation_Item> Orientation_Item { get; set; }
        public virtual DbSet<Orientation_Kind_Of_Successor> Orientation_Kind_Of_Successor { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Payment_Status> Payment_Status { get; set; }
        public virtual DbSet<PostNew_GroupTrainee> PostNew_GroupTrainee { get; set; }
        public virtual DbSet<Postnew> Postnews { get; set; }
        public virtual DbSet<Postnews_Category> Postnews_Category { get; set; }
        public virtual DbSet<PotentialSuccessor> PotentialSuccessors { get; set; }
        public virtual DbSet<PotentialSuccessors_Item> PotentialSuccessors_Item { get; set; }
        public virtual DbSet<PROCESS_Approver> PROCESS_Approver { get; set; }
        public virtual DbSet<PROCESS_StepRequirement> PROCESS_StepRequirement { get; set; }
        public virtual DbSet<PROCESS_Steps> PROCESS_Steps { get; set; }
        public virtual DbSet<Rec_Account> Rec_Account { get; set; }
        public virtual DbSet<Rec_AdvertisingPartner> Rec_AdvertisingPartner { get; set; }
        public virtual DbSet<Rec_Company> Rec_Company { get; set; }
        public virtual DbSet<Rec_Company_Account> Rec_Company_Account { get; set; }
        public virtual DbSet<Rec_Level> Rec_Level { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<ROLE_FUNCTION> ROLE_FUNCTION { get; set; }
        public virtual DbSet<ROLE2> ROLE2 { get; set; }
        public virtual DbSet<ROLEMENU> ROLEMENUs { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Room_Booking> Room_Booking { get; set; }
        public virtual DbSet<Room_Type> Room_Type { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Schedules_destination> Schedules_destination { get; set; }
        public virtual DbSet<Schedules_Method> Schedules_Method { get; set; }
        public virtual DbSet<Schedules_Type> Schedules_Type { get; set; }
        public virtual DbSet<SentMailUser> SentMailUsers { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Subject_Score> Subject_Score { get; set; }
        public virtual DbSet<Subject_TrainingCenter> Subject_TrainingCenter { get; set; }
        public virtual DbSet<SubjectDetail> SubjectDetails { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<SurveyLM> SurveyLMS { get; set; }
        public virtual DbSet<SurveyLMS_Item> SurveyLMS_Item { get; set; }
        public virtual DbSet<SurveyLMS_Question> SurveyLMS_Question { get; set; }
        public virtual DbSet<SYS_LogEvent> SYS_LogEvent { get; set; }
        public virtual DbSet<Title_Standard> Title_Standard { get; set; }
        public virtual DbSet<TMS_Approval_Type> TMS_Approval_Type { get; set; }
        public virtual DbSet<TMS_Approve_Department> TMS_Approve_Department { get; set; }
        public virtual DbSet<TMS_APPROVES> TMS_APPROVES { get; set; }
        public virtual DbSet<TMS_APPROVES_HISTORY> TMS_APPROVES_HISTORY { get; set; }
        public virtual DbSet<TMS_APPROVES_LOG> TMS_APPROVES_LOG { get; set; }
        public virtual DbSet<TMS_CertificateApproved> TMS_CertificateApproved { get; set; }
        public virtual DbSet<TMS_CONTRACTS> TMS_CONTRACTS { get; set; }
        public virtual DbSet<TMS_Course_History> TMS_Course_History { get; set; }
        public virtual DbSet<TMS_Course_History_Detail> TMS_Course_History_Detail { get; set; }
        public virtual DbSet<TMS_Course_History_Member> TMS_Course_History_Member { get; set; }
        public virtual DbSet<TMS_Course_History_Result> TMS_Course_History_Result { get; set; }
        public virtual DbSet<TMS_Course_Member> TMS_Course_Member { get; set; }
        public virtual DbSet<TMS_Course_Member_new> TMS_Course_Member_new { get; set; }
        public virtual DbSet<TMS_Course_Member_Remark> TMS_Course_Member_Remark { get; set; }
        public virtual DbSet<TMS_EMPLOYEE> TMS_EMPLOYEE { get; set; }
        public virtual DbSet<TMS_EMPLOYEE_DETAIL> TMS_EMPLOYEE_DETAIL { get; set; }
        public virtual DbSet<TMS_EXTERNAL_EDUCATION> TMS_EXTERNAL_EDUCATION { get; set; }
        public virtual DbSet<TMS_Grade> TMS_Grade { get; set; }
        public virtual DbSet<TMS_INSTRUTOR_CONTRACT> TMS_INSTRUTOR_CONTRACT { get; set; }
        public virtual DbSet<TMS_ROLE> TMS_ROLE { get; set; }
        public virtual DbSet<TMS_ROOM_SUBJECT> TMS_ROOM_SUBJECT { get; set; }
        public virtual DbSet<TMS_SCHEDULE> TMS_SCHEDULE { get; set; }
        public virtual DbSet<TMS_SentEmail> TMS_SentEmail { get; set; }
        public virtual DbSet<TMS_Subject_Grade> TMS_Subject_Grade { get; set; }
        public virtual DbSet<Trainee> Trainees { get; set; }
        public virtual DbSet<Trainee_Contract> Trainee_Contract { get; set; }
        public virtual DbSet<Trainee_Portal> Trainee_Portal { get; set; }
        public virtual DbSet<Trainee_Record> Trainee_Record { get; set; }
        public virtual DbSet<Trainee_TrainingCenter> Trainee_TrainingCenter { get; set; }
        public virtual DbSet<Trainee_Type> Trainee_Type { get; set; }
        public virtual DbSet<Trainee_Upload_Files> Trainee_Upload_Files { get; set; }
        public virtual DbSet<TraineeFuture> TraineeFutures { get; set; }
        public virtual DbSet<TraineeFuture_Item> TraineeFuture_Item { get; set; }
        public virtual DbSet<TraineeHistory> TraineeHistories { get; set; }
        public virtual DbSet<TraineeHistory_Item> TraineeHistory_Item { get; set; }
        public virtual DbSet<TrainingProgam_Cost> TrainingProgam_Cost { get; set; }
        public virtual DbSet<Transaction_Course_Trainee> Transaction_Course_Trainee { get; set; }
        public virtual DbSet<Transaction_Type> Transaction_Type { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<USER_HIS> USER_HIS { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<Course_Result_Final_Temp> Course_Result_Final_Temp { get; set; }
    
        public virtual ObjectResult<AspNet_SqlCachePollingStoredProcedure_Result> AspNet_SqlCachePollingStoredProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AspNet_SqlCachePollingStoredProcedure_Result>("AspNet_SqlCachePollingStoredProcedure");
        }
    
        public virtual ObjectResult<string> AspNet_SqlCacheQueryRegisteredTablesStoredProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AspNet_SqlCacheQueryRegisteredTablesStoredProcedure");
        }
    
        public virtual int AspNet_SqlCacheRegisterTableStoredProcedure(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AspNet_SqlCacheRegisterTableStoredProcedure", tableNameParameter);
        }
    
        public virtual int AspNet_SqlCacheUnRegisterTableStoredProcedure(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AspNet_SqlCacheUnRegisterTableStoredProcedure", tableNameParameter);
        }
    
        public virtual int AspNet_SqlCacheUpdateChangeIdStoredProcedure(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AspNet_SqlCacheUpdateChangeIdStoredProcedure", tableNameParameter);
        }
    
        public virtual ObjectResult<CheckTraineeExsist_Result> CheckTraineeExsist(Nullable<int> type, string check)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            var checkParameter = check != null ?
                new ObjectParameter("check", check) :
                new ObjectParameter("check", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckTraineeExsist_Result>("CheckTraineeExsist", typeParameter, checkParameter);
        }
    
        public virtual int CreateTempTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateTempTables");
        }
    
        public virtual int DeleteExpiredSessions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteExpiredSessions");
        }
    
        public virtual ObjectResult<GetDeparmentById_Result> GetDeparmentById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDeparmentById_Result>("GetDeparmentById", idParameter);
        }
    
        public virtual int GetHashCode(string input, ObjectParameter hash)
        {
            var inputParameter = input != null ?
                new ObjectParameter("input", input) :
                new ObjectParameter("input", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetHashCode", inputParameter, hash);
        }
    
        public virtual ObjectResult<GetJobTitleById_Result> GetJobTitleById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetJobTitleById_Result>("GetJobTitleById", idParameter);
        }
    
        public virtual ObjectResult<GetListSentMailUser_Result> GetListSentMailUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListSentMailUser_Result>("GetListSentMailUser");
        }
    
        public virtual int GetMajorVersion(ObjectParameter p_ver)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetMajorVersion", p_ver);
        }
    
        public virtual int RunJobTitle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RunJobTitle");
        }
    
        public virtual ObjectResult<sp_Attendance_Sheet_Result> sp_Attendance_Sheet(Nullable<int> courseId)
        {
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Attendance_Sheet_Result>("sp_Attendance_Sheet", courseIdParameter);
        }
    
        public virtual ObjectResult<sp_CourseInformation_Result> sp_CourseInformation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CourseInformation_Result>("sp_CourseInformation");
        }
    
        public virtual ObjectResult<sp_EmployeeRecord_Result> sp_EmployeeRecord()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_EmployeeRecord_Result>("sp_EmployeeRecord");
        }
    
        public virtual ObjectResult<sp_EmployeeRecord_External_Result> sp_EmployeeRecord_External()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_EmployeeRecord_External_Result>("sp_EmployeeRecord_External");
        }
    
        public virtual ObjectResult<sp_EmployeeRecord_Internal_Result> sp_EmployeeRecord_Internal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_EmployeeRecord_Internal_Result>("sp_EmployeeRecord_Internal");
        }
    
        public virtual ObjectResult<sp_GetCostDetail_Result> sp_GetCostDetail(string listCourseID, Nullable<System.DateTime> fromDateOfStart, Nullable<System.DateTime> toDateOfStart, Nullable<System.DateTime> fromDateOfEnd, Nullable<System.DateTime> toDateOfEnd)
        {
            var listCourseIDParameter = listCourseID != null ?
                new ObjectParameter("ListCourseID", listCourseID) :
                new ObjectParameter("ListCourseID", typeof(string));
    
            var fromDateOfStartParameter = fromDateOfStart.HasValue ?
                new ObjectParameter("FromDateOfStart", fromDateOfStart) :
                new ObjectParameter("FromDateOfStart", typeof(System.DateTime));
    
            var toDateOfStartParameter = toDateOfStart.HasValue ?
                new ObjectParameter("ToDateOfStart", toDateOfStart) :
                new ObjectParameter("ToDateOfStart", typeof(System.DateTime));
    
            var fromDateOfEndParameter = fromDateOfEnd.HasValue ?
                new ObjectParameter("FromDateOfEnd", fromDateOfEnd) :
                new ObjectParameter("FromDateOfEnd", typeof(System.DateTime));
    
            var toDateOfEndParameter = toDateOfEnd.HasValue ?
                new ObjectParameter("ToDateOfEnd", toDateOfEnd) :
                new ObjectParameter("ToDateOfEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCostDetail_Result>("sp_GetCostDetail", listCourseIDParameter, fromDateOfStartParameter, toDateOfStartParameter, fromDateOfEndParameter, toDateOfEndParameter);
        }
    
        public virtual ObjectResult<sp_GetCostHeader_Result> sp_GetCostHeader(string listCourseID, Nullable<System.DateTime> fromDateOfStart, Nullable<System.DateTime> toDateOfStart, Nullable<System.DateTime> fromDateOfEnd, Nullable<System.DateTime> toDateOfEnd)
        {
            var listCourseIDParameter = listCourseID != null ?
                new ObjectParameter("ListCourseID", listCourseID) :
                new ObjectParameter("ListCourseID", typeof(string));
    
            var fromDateOfStartParameter = fromDateOfStart.HasValue ?
                new ObjectParameter("FromDateOfStart", fromDateOfStart) :
                new ObjectParameter("FromDateOfStart", typeof(System.DateTime));
    
            var toDateOfStartParameter = toDateOfStart.HasValue ?
                new ObjectParameter("ToDateOfStart", toDateOfStart) :
                new ObjectParameter("ToDateOfStart", typeof(System.DateTime));
    
            var fromDateOfEndParameter = fromDateOfEnd.HasValue ?
                new ObjectParameter("FromDateOfEnd", fromDateOfEnd) :
                new ObjectParameter("FromDateOfEnd", typeof(System.DateTime));
    
            var toDateOfEndParameter = toDateOfEnd.HasValue ?
                new ObjectParameter("ToDateOfEnd", toDateOfEnd) :
                new ObjectParameter("ToDateOfEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCostHeader_Result>("sp_GetCostHeader", listCourseIDParameter, fromDateOfStartParameter, toDateOfStartParameter, fromDateOfEndParameter, toDateOfEndParameter);
        }
    
        public virtual int sp_GetFinalCourseResult(string listCourseID)
        {
            var listCourseIDParameter = listCourseID != null ?
                new ObjectParameter("ListCourseID", listCourseID) :
                new ObjectParameter("ListCourseID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetFinalCourseResult", listCourseIDParameter);
        }
    
        public virtual int sp_GetInstructor(string listSubjectId, string listInstructorId)
        {
            var listSubjectIdParameter = listSubjectId != null ?
                new ObjectParameter("ListSubjectId", listSubjectId) :
                new ObjectParameter("ListSubjectId", typeof(string));
    
            var listInstructorIdParameter = listInstructorId != null ?
                new ObjectParameter("ListInstructorId", listInstructorId) :
                new ObjectParameter("ListInstructorId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetInstructor", listSubjectIdParameter, listInstructorIdParameter);
        }
    
        public virtual ObjectResult<sp_GetTrainingDetail_Result> sp_GetTrainingDetail(string listID, string departmentCode, Nullable<System.DateTime> fromDateOfStart, Nullable<System.DateTime> toDateOfStart, Nullable<System.DateTime> fromDateOfEnd, Nullable<System.DateTime> toDateOfEnd, string status)
        {
            var listIDParameter = listID != null ?
                new ObjectParameter("ListID", listID) :
                new ObjectParameter("ListID", typeof(string));
    
            var departmentCodeParameter = departmentCode != null ?
                new ObjectParameter("DepartmentCode", departmentCode) :
                new ObjectParameter("DepartmentCode", typeof(string));
    
            var fromDateOfStartParameter = fromDateOfStart.HasValue ?
                new ObjectParameter("FromDateOfStart", fromDateOfStart) :
                new ObjectParameter("FromDateOfStart", typeof(System.DateTime));
    
            var toDateOfStartParameter = toDateOfStart.HasValue ?
                new ObjectParameter("ToDateOfStart", toDateOfStart) :
                new ObjectParameter("ToDateOfStart", typeof(System.DateTime));
    
            var fromDateOfEndParameter = fromDateOfEnd.HasValue ?
                new ObjectParameter("FromDateOfEnd", fromDateOfEnd) :
                new ObjectParameter("FromDateOfEnd", typeof(System.DateTime));
    
            var toDateOfEndParameter = toDateOfEnd.HasValue ?
                new ObjectParameter("ToDateOfEnd", toDateOfEnd) :
                new ObjectParameter("ToDateOfEnd", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTrainingDetail_Result>("sp_GetTrainingDetail", listIDParameter, departmentCodeParameter, fromDateOfStartParameter, toDateOfStartParameter, fromDateOfEndParameter, toDateOfEndParameter, statusParameter);
        }
    
        public virtual int sp_GetTrainingHeader(string listID, string departmentCode, Nullable<System.DateTime> fromDateOfStart, Nullable<System.DateTime> toDateOfStart, Nullable<System.DateTime> fromDateOfEnd, Nullable<System.DateTime> toDateOfEnd, string status)
        {
            var listIDParameter = listID != null ?
                new ObjectParameter("ListID", listID) :
                new ObjectParameter("ListID", typeof(string));
    
            var departmentCodeParameter = departmentCode != null ?
                new ObjectParameter("DepartmentCode", departmentCode) :
                new ObjectParameter("DepartmentCode", typeof(string));
    
            var fromDateOfStartParameter = fromDateOfStart.HasValue ?
                new ObjectParameter("FromDateOfStart", fromDateOfStart) :
                new ObjectParameter("FromDateOfStart", typeof(System.DateTime));
    
            var toDateOfStartParameter = toDateOfStart.HasValue ?
                new ObjectParameter("ToDateOfStart", toDateOfStart) :
                new ObjectParameter("ToDateOfStart", typeof(System.DateTime));
    
            var fromDateOfEndParameter = fromDateOfEnd.HasValue ?
                new ObjectParameter("FromDateOfEnd", fromDateOfEnd) :
                new ObjectParameter("FromDateOfEnd", typeof(System.DateTime));
    
            var toDateOfEndParameter = toDateOfEnd.HasValue ?
                new ObjectParameter("ToDateOfEnd", toDateOfEnd) :
                new ObjectParameter("ToDateOfEnd", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetTrainingHeader", listIDParameter, departmentCodeParameter, fromDateOfStartParameter, toDateOfStartParameter, fromDateOfEndParameter, toDateOfEndParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_TimeFrame_Result> sp_TimeFrame(Nullable<int> courseDetailId)
        {
            var courseDetailIdParameter = courseDetailId.HasValue ?
                new ObjectParameter("CourseDetailId", courseDetailId) :
                new ObjectParameter("CourseDetailId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimeFrame_Result>("sp_TimeFrame", courseDetailIdParameter);
        }
    
        public virtual ObjectResult<sp_TimeFrame_Full_Result> sp_TimeFrame_Full(Nullable<int> courseDetailId)
        {
            var courseDetailIdParameter = courseDetailId.HasValue ?
                new ObjectParameter("CourseDetailId", courseDetailId) :
                new ObjectParameter("CourseDetailId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimeFrame_Full_Result>("sp_TimeFrame_Full", courseDetailIdParameter);
        }
    
        [DbFunction("EFDbContext", "Split_tv")]
        public virtual IQueryable<Split_tv_Result> Split_tv(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_tv_Result>("[EFDbContext].[Split_tv](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        [DbFunction("EFDbContext", "SplitArray")]
        public virtual IQueryable<string> SplitArray(string inputString, string delimiter)
        {
            var inputStringParameter = inputString != null ?
                new ObjectParameter("InputString", inputString) :
                new ObjectParameter("InputString", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[EFDbContext].[SplitArray](@InputString, @Delimiter)", inputStringParameter, delimiterParameter);
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_7ac58fe3_52ef_44ac_b278_525e858d5770()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_7ac58fe3_52ef_44ac_b278_525e858d5770");
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_9cf37993_dcbc_4f15_be50_0ad5b1139d12()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_9cf37993_dcbc_4f15_be50_0ad5b1139d12");
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_b66759cd_9365_4b10_91b7_00d5f3454db1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_b66759cd_9365_4b10_91b7_00d5f3454db1");
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_d4243289_b1f7_4b01_ac2c_738b9cfd5a82()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_d4243289_b1f7_4b01_ac2c_738b9cfd5a82");
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_ded21560_1f6a_47c3_b645_bff5d40d72b8()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_ded21560_1f6a_47c3_b645_bff5d40d72b8");
        }
    
        public virtual int TempGetAppID(string appName, ObjectParameter appId)
        {
            var appNameParameter = appName != null ?
                new ObjectParameter("appName", appName) :
                new ObjectParameter("appName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempGetAppID", appNameParameter, appId);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItem(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockDate, ObjectParameter lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItem", idParameter, itemShort, locked, lockDate, lockCookie);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItem2(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockAge, ObjectParameter lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItem2", idParameter, itemShort, locked, lockAge, lockCookie);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItem3(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockAge, ObjectParameter lockCookie, ObjectParameter actionFlags)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItem3", idParameter, itemShort, locked, lockAge, lockCookie, actionFlags);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItemExclusive(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockDate, ObjectParameter lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItemExclusive", idParameter, itemShort, locked, lockDate, lockCookie);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItemExclusive2(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockAge, ObjectParameter lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItemExclusive2", idParameter, itemShort, locked, lockAge, lockCookie);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItemExclusive3(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockAge, ObjectParameter lockCookie, ObjectParameter actionFlags)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItemExclusive3", idParameter, itemShort, locked, lockAge, lockCookie, actionFlags);
        }
    
        public virtual int TempGetVersion(ObjectParameter ver)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempGetVersion", ver);
        }
    
        public virtual int TempInsertStateItemLong(string id, byte[] itemLong, Nullable<int> timeout)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemLongParameter = itemLong != null ?
                new ObjectParameter("itemLong", itemLong) :
                new ObjectParameter("itemLong", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempInsertStateItemLong", idParameter, itemLongParameter, timeoutParameter);
        }
    
        public virtual int TempInsertStateItemShort(string id, byte[] itemShort, Nullable<int> timeout)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemShortParameter = itemShort != null ?
                new ObjectParameter("itemShort", itemShort) :
                new ObjectParameter("itemShort", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempInsertStateItemShort", idParameter, itemShortParameter, timeoutParameter);
        }
    
        public virtual int TempInsertUninitializedItem(string id, byte[] itemShort, Nullable<int> timeout)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemShortParameter = itemShort != null ?
                new ObjectParameter("itemShort", itemShort) :
                new ObjectParameter("itemShort", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempInsertUninitializedItem", idParameter, itemShortParameter, timeoutParameter);
        }
    
        public virtual int TempReleaseStateItemExclusive(string id, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempReleaseStateItemExclusive", idParameter, lockCookieParameter);
        }
    
        public virtual int TempRemoveStateItem(string id, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempRemoveStateItem", idParameter, lockCookieParameter);
        }
    
        public virtual int TempResetTimeout(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempResetTimeout", idParameter);
        }
    
        public virtual int TempUpdateStateItemLong(string id, byte[] itemLong, Nullable<int> timeout, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemLongParameter = itemLong != null ?
                new ObjectParameter("itemLong", itemLong) :
                new ObjectParameter("itemLong", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempUpdateStateItemLong", idParameter, itemLongParameter, timeoutParameter, lockCookieParameter);
        }
    
        public virtual int TempUpdateStateItemLongNullShort(string id, byte[] itemLong, Nullable<int> timeout, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemLongParameter = itemLong != null ?
                new ObjectParameter("itemLong", itemLong) :
                new ObjectParameter("itemLong", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempUpdateStateItemLongNullShort", idParameter, itemLongParameter, timeoutParameter, lockCookieParameter);
        }
    
        public virtual int TempUpdateStateItemShort(string id, byte[] itemShort, Nullable<int> timeout, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemShortParameter = itemShort != null ?
                new ObjectParameter("itemShort", itemShort) :
                new ObjectParameter("itemShort", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempUpdateStateItemShort", idParameter, itemShortParameter, timeoutParameter, lockCookieParameter);
        }
    
        public virtual int TempUpdateStateItemShortNullLong(string id, byte[] itemShort, Nullable<int> timeout, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemShortParameter = itemShort != null ?
                new ObjectParameter("itemShort", itemShort) :
                new ObjectParameter("itemShort", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempUpdateStateItemShortNullLong", idParameter, itemShortParameter, timeoutParameter, lockCookieParameter);
        }
    
        public virtual int UpdateSentMailUser(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateSentMailUser", emailParameter);
        }
    
        [DbFunction("EFDbContext", "Split")]
        public virtual IQueryable<Split_Result> Split(string inputString, string delimiter)
        {
            var inputStringParameter = inputString != null ?
                new ObjectParameter("InputString", inputString) :
                new ObjectParameter("InputString", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[EFDbContext].[Split](@InputString, @Delimiter)", inputStringParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<sp_GetListEmployee_TV_Result> sp_GetListEmployee_TV(string filterCodeOrName)
        {
            var filterCodeOrNameParameter = filterCodeOrName != null ?
                new ObjectParameter("filterCodeOrName", filterCodeOrName) :
                new ObjectParameter("filterCodeOrName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetListEmployee_TV_Result>("sp_GetListEmployee_TV", filterCodeOrNameParameter);
        }
    
        public virtual ObjectResult<sp_UpdateDataFinal_TV_Result> sp_UpdateDataFinal_TV(Nullable<int> traineeId, Nullable<int> courseId)
        {
            var traineeIdParameter = traineeId.HasValue ?
                new ObjectParameter("traineeId", traineeId) :
                new ObjectParameter("traineeId", typeof(int));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_UpdateDataFinal_TV_Result>("sp_UpdateDataFinal_TV", traineeIdParameter, courseIdParameter);
        }
    
        public virtual ObjectResult<sp_GetSubjectResult_TV_Result> sp_GetSubjectResult_TV(Nullable<int> courseDetailId)
        {
            var courseDetailIdParameter = courseDetailId.HasValue ?
                new ObjectParameter("courseDetailId", courseDetailId) :
                new ObjectParameter("courseDetailId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSubjectResult_TV_Result>("sp_GetSubjectResult_TV", courseDetailIdParameter);
        }
    
        public virtual ObjectResult<sp_GetDetail_TV_Result> sp_GetDetail_TV(string venue, string courseCode, string courseName, Nullable<int> departmentid, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, string courids, Nullable<int> courseID)
        {
            var venueParameter = venue != null ?
                new ObjectParameter("venue", venue) :
                new ObjectParameter("venue", typeof(string));
    
            var courseCodeParameter = courseCode != null ?
                new ObjectParameter("courseCode", courseCode) :
                new ObjectParameter("courseCode", typeof(string));
    
            var courseNameParameter = courseName != null ?
                new ObjectParameter("courseName", courseName) :
                new ObjectParameter("courseName", typeof(string));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("dateTo", dateTo) :
                new ObjectParameter("dateTo", typeof(System.DateTime));
    
            var couridsParameter = courids != null ?
                new ObjectParameter("courids", courids) :
                new ObjectParameter("courids", typeof(string));
    
            var courseIDParameter = courseID.HasValue ?
                new ObjectParameter("CourseID", courseID) :
                new ObjectParameter("CourseID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDetail_TV_Result>("sp_GetDetail_TV", venueParameter, courseCodeParameter, courseNameParameter, departmentidParameter, dateFromParameter, dateToParameter, couridsParameter, courseIDParameter);
        }
    
        public virtual ObjectResult<sp_GetTrainingHeaderTV_Result> sp_GetTrainingHeaderTV(string listID, string departmentCode, Nullable<System.DateTime> fromDateOfStart, Nullable<System.DateTime> toDateOfStart, Nullable<System.DateTime> fromDateOfEnd, Nullable<System.DateTime> toDateOfEnd, string status)
        {
            var listIDParameter = listID != null ?
                new ObjectParameter("ListID", listID) :
                new ObjectParameter("ListID", typeof(string));
    
            var departmentCodeParameter = departmentCode != null ?
                new ObjectParameter("DepartmentCode", departmentCode) :
                new ObjectParameter("DepartmentCode", typeof(string));
    
            var fromDateOfStartParameter = fromDateOfStart.HasValue ?
                new ObjectParameter("FromDateOfStart", fromDateOfStart) :
                new ObjectParameter("FromDateOfStart", typeof(System.DateTime));
    
            var toDateOfStartParameter = toDateOfStart.HasValue ?
                new ObjectParameter("ToDateOfStart", toDateOfStart) :
                new ObjectParameter("ToDateOfStart", typeof(System.DateTime));
    
            var fromDateOfEndParameter = fromDateOfEnd.HasValue ?
                new ObjectParameter("FromDateOfEnd", fromDateOfEnd) :
                new ObjectParameter("FromDateOfEnd", typeof(System.DateTime));
    
            var toDateOfEndParameter = toDateOfEnd.HasValue ?
                new ObjectParameter("ToDateOfEnd", toDateOfEnd) :
                new ObjectParameter("ToDateOfEnd", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTrainingHeaderTV_Result>("sp_GetTrainingHeaderTV", listIDParameter, departmentCodeParameter, fromDateOfStartParameter, toDateOfStartParameter, fromDateOfEndParameter, toDateOfEndParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_Reminder_TV_Result> sp_Reminder_TV(string departlist, string listJobtitle, string subjectName, string subjectCode, Nullable<System.DateTime> dateFrom, Nullable<int> nom)
        {
            var departlistParameter = departlist != null ?
                new ObjectParameter("departlist", departlist) :
                new ObjectParameter("departlist", typeof(string));
    
            var listJobtitleParameter = listJobtitle != null ?
                new ObjectParameter("listJobtitle", listJobtitle) :
                new ObjectParameter("listJobtitle", typeof(string));
    
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("subjectName", subjectName) :
                new ObjectParameter("subjectName", typeof(string));
    
            var subjectCodeParameter = subjectCode != null ?
                new ObjectParameter("subjectCode", subjectCode) :
                new ObjectParameter("subjectCode", typeof(string));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var nomParameter = nom.HasValue ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Reminder_TV_Result>("sp_Reminder_TV", departlistParameter, listJobtitleParameter, subjectNameParameter, subjectCodeParameter, dateFromParameter, nomParameter);
        }
    
        public virtual ObjectResult<sp_GetInstructorReport_TV_Result> sp_GetInstructorReport_TV(string subjectName, string subjectCode, string traineeName, string traineeCode, Nullable<int> departmentID, Nullable<int> jobtitleID, string sortDirection, string orderingFunction)
        {
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("subjectName", subjectName) :
                new ObjectParameter("subjectName", typeof(string));
    
            var subjectCodeParameter = subjectCode != null ?
                new ObjectParameter("subjectCode", subjectCode) :
                new ObjectParameter("subjectCode", typeof(string));
    
            var traineeNameParameter = traineeName != null ?
                new ObjectParameter("traineeName", traineeName) :
                new ObjectParameter("traineeName", typeof(string));
    
            var traineeCodeParameter = traineeCode != null ?
                new ObjectParameter("traineeCode", traineeCode) :
                new ObjectParameter("traineeCode", typeof(string));
    
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("departmentID", departmentID) :
                new ObjectParameter("departmentID", typeof(int));
    
            var jobtitleIDParameter = jobtitleID.HasValue ?
                new ObjectParameter("jobtitleID", jobtitleID) :
                new ObjectParameter("jobtitleID", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("sortDirection", sortDirection) :
                new ObjectParameter("sortDirection", typeof(string));
    
            var orderingFunctionParameter = orderingFunction != null ?
                new ObjectParameter("orderingFunction", orderingFunction) :
                new ObjectParameter("orderingFunction", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetInstructorReport_TV_Result>("sp_GetInstructorReport_TV", subjectNameParameter, subjectCodeParameter, traineeNameParameter, traineeCodeParameter, departmentIDParameter, jobtitleIDParameter, sortDirectionParameter, orderingFunctionParameter);
        }
    
        public virtual ObjectResult<sp_UpdateDataFinal_TV1_Result> sp_UpdateDataFinal_TV1(Nullable<int> traineeId, Nullable<int> courseId)
        {
            var traineeIdParameter = traineeId.HasValue ?
                new ObjectParameter("traineeId", traineeId) :
                new ObjectParameter("traineeId", typeof(int));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_UpdateDataFinal_TV1_Result>("sp_UpdateDataFinal_TV1", traineeIdParameter, courseIdParameter);
        }
    }
}
