//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public Nullable<int> Instructor_Id { get; set; }
        public Nullable<int> CourseDetail_Id { get; set; }
        public Nullable<int> Method_Id { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Is_Cancel { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Pay_DateFrom_DateRequest { get; set; }
        public Nullable<System.DateTime> Pay_DateTo_Date_Request { get; set; }
        public Nullable<System.DateTime> Pay_DateFrom_DateApproval { get; set; }
        public Nullable<System.DateTime> Pay_DateTo_DateApproval { get; set; }
        public Nullable<int> TypeInstructor { get; set; }
    
        public virtual Course_Detail Course_Detail { get; set; }
        public virtual Payment_Status Payment_Status { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
