//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS_Approver
    {
        public int Id { get; set; }
        public Nullable<int> Step { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsDeteled { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
