//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rec_Company_Account
    {
        public int Id { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> Company_PartnerID { get; set; }
        public string str_Email { get; set; }
        public string str_Password { get; set; }
        public Nullable<System.DateTime> dtm_Expiredate { get; set; }
    
        public virtual Rec_Account Rec_Account { get; set; }
        public virtual Rec_Company Rec_Company { get; set; }
    }
}
