//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_FUNCTION
    {
        public int id { get; set; }
        public Nullable<int> int_Page_id { get; set; }
        public Nullable<int> int_Role_id { get; set; }
        public Nullable<bool> bit_view { get; set; }
        public Nullable<bool> bit_create { get; set; }
        public Nullable<bool> bit_update { get; set; }
        public Nullable<bool> bit_delete { get; set; }
        public Nullable<bool> bit_active_deactive { get; set; }
    
        public virtual ROLE ROLE { get; set; }
    }
}
