//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLEMENU
    {
        public int ID { get; set; }
        public Nullable<int> GroupFunctionId { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public Nullable<int> MenuType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual GroupFunction GroupFunction { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
