//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Course_Blended_Learning = new HashSet<Course_Blended_Learning>();
            this.Course_Detail = new HashSet<Course_Detail>();
            this.Course_Detail_Room = new HashSet<Course_Detail_Room>();
            this.Management_Room_Item = new HashSet<Management_Room_Item>();
            this.Meetings = new HashSet<Meeting>();
            this.Room_Booking = new HashSet<Room_Booking>();
            this.TMS_ROOM_SUBJECT = new HashSet<TMS_ROOM_SUBJECT>();
        }
    
        public int Room_Id { get; set; }
        public string str_Name { get; set; }
        public Nullable<int> int_Capacity { get; set; }
        public string str_Equipment { get; set; }
        public string int_Area { get; set; }
        public string str_Location { get; set; }
        public bool bit_Deleted { get; set; }
        public Nullable<System.DateTime> dtm_Created_At { get; set; }
        public string str_Created_By { get; set; }
        public Nullable<System.DateTime> dtm_Modified_At { get; set; }
        public string str_Modified_By { get; set; }
        public Nullable<System.DateTime> dtm_Deleted_At { get; set; }
        public string str_Deleted_By { get; set; }
        public string str_code { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> is_Meeting { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Blended_Learning> Course_Blended_Learning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Detail> Course_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Detail_Room> Course_Detail_Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Management_Room_Item> Management_Room_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting> Meetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room_Booking> Room_Booking { get; set; }
        public virtual Room_Type Room_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_ROOM_SUBJECT> TMS_ROOM_SUBJECT { get; set; }
    }
}
