//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules_Method
    {
        public int Id { get; set; }
        public Nullable<int> IdMethod { get; set; }
        public Nullable<int> IdSchedule { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
