//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules_destination
    {
        public int Id { get; set; }
        public Nullable<bool> IsUser { get; set; }
        public Nullable<int> IdEmp { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdSchedule { get; set; }
        public Nullable<bool> IsAll { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual USER USER { get; set; }
    }
}
