//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules_Type
    {
        public int Id { get; set; }
        public Nullable<int> IdType { get; set; }
        public Nullable<int> IdSchedule { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<int> IdTimeMark { get; set; }
        public Nullable<int> TimeRemind { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
