//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubjectDetail()
        {
            this.CAT_GROUPSUBJECT_ITEM = new HashSet<CAT_GROUPSUBJECT_ITEM>();
            this.Course_Cost = new HashSet<Course_Cost>();
            this.Course_Detail = new HashSet<Course_Detail>();
            this.Course_Detail_Subject_Note = new HashSet<Course_Detail_Subject_Note>();
            this.Course_Result = new HashSet<Course_Result>();
            this.Course_Result_Temp = new HashSet<Course_Result_Temp>();
            this.Course_Subject_Item = new HashSet<Course_Subject_Item>();
            this.Examiner_Ability = new HashSet<Examiner_Ability>();
            this.Group_Certificate_Schedule_Detail = new HashSet<Group_Certificate_Schedule_Detail>();
            this.Instructor_Ability = new HashSet<Instructor_Ability>();
            this.Orientation_Item = new HashSet<Orientation_Item>();
            this.Subject_Score = new HashSet<Subject_Score>();
            this.Subject_TrainingCenter = new HashSet<Subject_TrainingCenter>();
            this.SubjectDetail1 = new HashSet<SubjectDetail>();
            this.Title_Standard = new HashSet<Title_Standard>();
            this.TMS_Course_History_Detail = new HashSet<TMS_Course_History_Detail>();
            this.TMS_Course_History_Result = new HashSet<TMS_Course_History_Result>();
            this.TMS_ROOM_SUBJECT = new HashSet<TMS_ROOM_SUBJECT>();
            this.TraineeFuture_Item = new HashSet<TraineeFuture_Item>();
            this.TraineeHistory_Item = new HashSet<TraineeHistory_Item>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SubjectHeaderId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<int> CourseTypeId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string Ancesstor { get; set; }
        public Nullable<bool> IsAverageCalculate { get; set; }
        public Nullable<int> RefreshCycle { get; set; }
        public Nullable<bool> ScoreOrResult { get; set; }
        public Nullable<double> PassScore { get; set; }
        public Nullable<int> LmsStatus { get; set; }
        public Nullable<double> Excellent_Score { get; set; }
        public Nullable<int> int_Parent_Id { get; set; }
        public Nullable<int> int_GroupSubject_id { get; set; }
        public string CertificateName { get; set; }
        public string CertificateCode { get; set; }
    
        public virtual CAT_GROUPSUBJECT CAT_GROUPSUBJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_GROUPSUBJECT_ITEM> CAT_GROUPSUBJECT_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Cost> Course_Cost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Detail> Course_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Detail_Subject_Note> Course_Detail_Subject_Note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Result> Course_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Result_Temp> Course_Result_Temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Subject_Item> Course_Subject_Item { get; set; }
        public virtual Course_Type Course_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examiner_Ability> Examiner_Ability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_Certificate_Schedule_Detail> Group_Certificate_Schedule_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instructor_Ability> Instructor_Ability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orientation_Item> Orientation_Item { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject_Score> Subject_Score { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject_TrainingCenter> Subject_TrainingCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectDetail> SubjectDetail1 { get; set; }
        public virtual SubjectDetail SubjectDetail2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Title_Standard> Title_Standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_Course_History_Detail> TMS_Course_History_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_Course_History_Result> TMS_Course_History_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_ROOM_SUBJECT> TMS_ROOM_SUBJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraineeFuture_Item> TraineeFuture_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraineeHistory_Item> TraineeHistory_Item { get; set; }
    }
}
