//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyLMS_Question
    {
        public int id { get; set; }
        public Nullable<int> idsurvey { get; set; }
        public string name { get; set; }
        public string name_type { get; set; }
        public string content_question { get; set; }
    
        public virtual SurveyLM SurveyLM { get; set; }
    }
}
