//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> Resp_View { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Modify_At { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Modify_By { get; set; }
        public Nullable<int> LMSStatus { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<System.DateTime> Deleted_At { get; set; }
        public Nullable<int> Deleted_By { get; set; }
    }
}
