//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyLMS_Item
    {
        public int id { get; set; }
        public Nullable<int> survey_id { get; set; }
        public Nullable<int> trainee_id { get; set; }
    
        public virtual SurveyLM SurveyLM { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
