//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_LogEvent
    {
        public int Id { get; set; }
        public Nullable<int> LogType { get; set; }
        public Nullable<int> LogEvent { get; set; }
        public string Source { get; set; }
        public Nullable<int> UserName { get; set; }
        public string IP { get; set; }
        public string Content { get; set; }
        public string PageID { get; set; }
        public string RawUrl { get; set; }
        public string FullUrl { get; set; }
        public string ServerName { get; set; }
        public string ClientInfo { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
