//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_EXTERNAL_EDUCATION
    {
        public int id { get; set; }
        public Nullable<int> id_user { get; set; }
        public string course { get; set; }
        public string time { get; set; }
        public string organization { get; set; }
        public string note { get; set; }
        public string filepath { get; set; }
    }
}
