//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_APPROVES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMS_APPROVES()
        {
            this.TMS_APPROVES_HISTORY = new HashSet<TMS_APPROVES_HISTORY>();
        }
    
        public int id { get; set; }
        public Nullable<int> int_id_status { get; set; }
        public string str_Code { get; set; }
        public Nullable<int> int_Course_id { get; set; }
        public Nullable<int> int_Type { get; set; }
        public Nullable<int> int_Approve_by { get; set; }
        public Nullable<int> int_Requested_by { get; set; }
        public Nullable<System.DateTime> dtm_requested_date { get; set; }
        public Nullable<int> int_Seq { get; set; }
        public Nullable<int> int_version { get; set; }
        public string str_ResonReject { get; set; }
        public Nullable<int> int_courseDetails_Id { get; set; }
        public Nullable<System.DateTime> Date_Approved { get; set; }
        public Nullable<System.DateTime> Date_Requested { get; set; }
        public string str_Remark { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Course_Detail Course_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_APPROVES_HISTORY> TMS_APPROVES_HISTORY { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
