//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMS_EMPLOYEE()
        {
            this.TMS_INSTRUTOR_CONTRACT = new HashSet<TMS_INSTRUTOR_CONTRACT>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_role { get; set; }
        public Nullable<int> id_department { get; set; }
        public Nullable<int> id_jobtitle { get; set; }
        public Nullable<int> id_nationality { get; set; }
        public Nullable<int> id_partner { get; set; }
        public Nullable<int> id_gender { get; set; }
        public Nullable<int> id_type { get; set; }
        public Nullable<int> id_company { get; set; }
    
        public virtual TMS_EMPLOYEE_DETAIL TMS_EMPLOYEE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_INSTRUTOR_CONTRACT> TMS_INSTRUTOR_CONTRACT { get; set; }
    }
}
