//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_Course_History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMS_Course_History()
        {
            this.TMS_Course_History_Detail = new HashSet<TMS_Course_History_Detail>();
            this.TMS_Course_History_Member = new HashSet<TMS_Course_History_Member>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public Nullable<int> Version { get; set; }
        public string str_Name { get; set; }
        public string str_Code { get; set; }
        public Nullable<int> Job_Title_Id { get; set; }
        public Nullable<System.DateTime> dtm_StartDate { get; set; }
        public Nullable<System.DateTime> dtm_EndDate { get; set; }
        public Nullable<int> int_Status { get; set; }
        public Nullable<int> Course_Type_Id { get; set; }
        public Nullable<System.DateTime> dtm_Created_At { get; set; }
        public string str_Created_By { get; set; }
        public Nullable<System.DateTime> dtm_Modified_At { get; set; }
        public string str_Modified_By { get; set; }
        public Nullable<System.DateTime> dtm_Deleted_At { get; set; }
        public string str_Deleted_By { get; set; }
        public string venue { get; set; }
        public Nullable<int> int_StatusNew { get; set; }
        public Nullable<int> int_type_result { get; set; }
        public Nullable<bool> type { get; set; }
        public Nullable<bool> survey { get; set; }
        public Nullable<int> parent_course_id { get; set; }
        public Nullable<int> partner_id { get; set; }
        public Nullable<int> no_trainee { get; set; }
        public string note { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_Course_History_Detail> TMS_Course_History_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_Course_History_Member> TMS_Course_History_Member { get; set; }
    }
}
