//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_SCHEDULE
    {
        public int Schedule_id { get; set; }
        public Nullable<int> int_Course_Details_Id { get; set; }
        public Nullable<int> int_Room_id { get; set; }
        public Nullable<System.DateTime> tim_Start_Time { get; set; }
        public Nullable<System.DateTime> tim_End_Time { get; set; }
        public string str_Note { get; set; }
        public Nullable<int> int_Order { get; set; }
        public Nullable<int> int_Status { get; set; }
    
        public virtual Course_Detail Course_Detail { get; set; }
    }
}
