//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_CONTRACTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMS_CONTRACTS()
        {
            this.TMS_INSTRUTOR_CONTRACT = new HashSet<TMS_INSTRUTOR_CONTRACT>();
        }
    
        public int id { get; set; }
        public Nullable<int> int_Id_contractor { get; set; }
        public Nullable<int> int_Id_status { get; set; }
        public Nullable<int> int_Id_type { get; set; }
        public string str_Code { get; set; }
        public string str_Contractno { get; set; }
        public string str_Description { get; set; }
        public Nullable<System.DateTime> dtm_Signdate { get; set; }
        public Nullable<System.DateTime> dtm_Expiredate { get; set; }
        public string str_Filepath { get; set; }
        public string str_Note { get; set; }
        public Nullable<decimal> mon_Price { get; set; }
        public Nullable<System.DateTime> dtm_Created_date { get; set; }
        public Nullable<int> int_Created_by { get; set; }
        public Nullable<System.DateTime> dtm_Last_updated_date { get; set; }
        public Nullable<int> int_Last_updated_by { get; set; }
        public Nullable<bool> bit_Is_active { get; set; }
        public Nullable<int> Currency { get; set; }
        public bool isDelete { get; set; }
    
        public virtual CAT_CONTRACTOR CAT_CONTRACTOR { get; set; }
        public virtual CAT_CONTRACTS_STATUS CAT_CONTRACTS_STATUS { get; set; }
        public virtual CAT_CONTRACTS_TYPE CAT_CONTRACTS_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_INSTRUTOR_CONTRACT> TMS_INSTRUTOR_CONTRACT { get; set; }
    }
}
