//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_APPROVES_HISTORY
    {
        public int id { get; set; }
        public Nullable<int> approves_id { get; set; }
        public Nullable<int> int_id_status { get; set; }
        public Nullable<int> int_Course_id { get; set; }
        public Nullable<int> int_Type { get; set; }
        public Nullable<int> int_Approve_by { get; set; }
        public Nullable<int> int_Requested_by { get; set; }
        public Nullable<System.DateTime> dtm_requested_date { get; set; }
        public Nullable<int> int_version { get; set; }
        public Nullable<int> int_courseDetails_Id { get; set; }
    
        public virtual TMS_APPROVES TMS_APPROVES { get; set; }
    }
}
