//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_EMPLOYEE_DETAIL
    {
        public int id { get; set; }
        public Nullable<int> id_user { get; set; }
        public string auth { get; set; }
        public Nullable<int> confirmed { get; set; }
        public Nullable<int> policyagreed { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<int> suspended { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> pob { get; set; }
        public Nullable<System.DateTime> doj { get; set; }
        public Nullable<int> idnumber { get; set; }
        public string passport { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string avatar { get; set; }
        public string emailstop { get; set; }
        public string icq { get; set; }
        public string skype { get; set; }
        public string yahoo { get; set; }
        public string aim { get; set; }
        public string msn { get; set; }
        public Nullable<int> phone1 { get; set; }
        public Nullable<int> phone2 { get; set; }
        public string institution { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string lang { get; set; }
        public string calendartype { get; set; }
        public Nullable<int> timezone { get; set; }
        public Nullable<System.DateTime> firstaccess { get; set; }
        public Nullable<System.DateTime> lastaccess { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public Nullable<System.DateTime> currentlogin { get; set; }
        public Nullable<int> lastip { get; set; }
        public string secret { get; set; }
        public Nullable<int> picture { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public Nullable<int> descriptionformat { get; set; }
        public Nullable<int> mailformat { get; set; }
        public Nullable<int> maildigest { get; set; }
        public Nullable<int> maildisplay { get; set; }
        public Nullable<int> autosubscribe { get; set; }
        public Nullable<int> trackforums { get; set; }
        public Nullable<System.DateTime> timecreated { get; set; }
        public Nullable<System.DateTime> timemodified { get; set; }
        public Nullable<int> trustbitmask { get; set; }
    
        public virtual TMS_EMPLOYEE TMS_EMPLOYEE { get; set; }
    }
}
