//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_Course_Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMS_Course_Member()
        {
            this.Course_Result = new HashSet<Course_Result>();
            this.Course_Result_Temp = new HashSet<Course_Result_Temp>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Member_Id { get; set; }
        public Nullable<int> Course_Details_Id { get; set; }
        public Nullable<int> Approve_Id { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> DeleteApprove { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Status { get; set; }
        public string AssignBy { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<int> LmsStatus { get; set; }
        public string Remark { get; set; }
    
        public virtual Course_Detail Course_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Result> Course_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Result_Temp> Course_Result_Temp { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
