//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_SentEmail
    {
        public int Id { get; set; }
        public string mail_receiver { get; set; }
        public Nullable<int> type_sent { get; set; }
        public Nullable<int> flag_sent { get; set; }
        public string subjectname { get; set; }
        public string content_body { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<int> id_sender { get; set; }
        public Nullable<int> id_course { get; set; }
        public Nullable<int> cat_mail_ID { get; set; }
        public Nullable<int> AttachFileType { get; set; }
        public Nullable<int> id_Schedule { get; set; }
        public Nullable<System.DateTime> time_sent { get; set; }
        public string LogError { get; set; }
    
        public virtual CAT_MAIL CAT_MAIL { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
