//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_Approve_Department
    {
        public int id { get; set; }
        public Nullable<int> Department_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Level { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual USER USER { get; set; }
    }
}
