//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingProgam_Cost
    {
        public int Id { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
