//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee_Contract
    {
        public int id { get; set; }
        public Nullable<int> Trainee_Id { get; set; }
        public string contractno { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> expire_date { get; set; }
        public Nullable<System.DateTime> dtm_Created_At { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Trainee Trainee { get; set; }
    }
}
