//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeFuture_Item
    {
        public int Id { get; set; }
        public Nullable<int> TraineeFutureId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual SubjectDetail SubjectDetail { get; set; }
        public virtual TraineeFuture TraineeFuture { get; set; }
    }
}
