//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TraineeHistory()
        {
            this.TraineeHistory_Item = new HashSet<TraineeHistory_Item>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Trainee_Id { get; set; }
        public Nullable<int> Job_Title_Id { get; set; }
        public Nullable<System.DateTime> dtm_Create_At { get; set; }
        public Nullable<int> dtm_Create_By { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> LmsStatus { get; set; }
    
        public virtual JobTitle JobTitle { get; set; }
        public virtual Trainee Trainee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraineeHistory_Item> TraineeHistory_Item { get; set; }
    }
}
