//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeFuture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TraineeFuture()
        {
            this.TraineeFuture_Item = new HashSet<TraineeFuture_Item>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TraineeId { get; set; }
        public Nullable<int> JobTitleId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> LmsStatus { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Schedule { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual JobTitle JobTitle { get; set; }
        public virtual Trainee Trainee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraineeFuture_Item> TraineeFuture_Item { get; set; }
    }
}
