//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee_Portal
    {
        public int Id { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> TraineeID { get; set; }
        public string TraineeUserName { get; set; }
        public string TraineeFullName { get; set; }
        public string CourseCode { get; set; }
        public string SubjectCode { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
