//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Course_Attendance = new HashSet<Course_Attendance>();
            this.Course_Blended_Learning = new HashSet<Course_Blended_Learning>();
            this.Course_Detail = new HashSet<Course_Detail>();
            this.Course_Detail_Instructor = new HashSet<Course_Detail_Instructor>();
            this.Course_Result = new HashSet<Course_Result>();
            this.Course_Result_Final = new HashSet<Course_Result_Final>();
            this.Course_Result_Summary = new HashSet<Course_Result_Summary>();
            this.Course_Result_Temp = new HashSet<Course_Result_Temp>();
            this.CourseRemarkCheckFails = new HashSet<CourseRemarkCheckFail>();
            this.Departments = new HashSet<Department>();
            this.Examiner_Ability = new HashSet<Examiner_Ability>();
            this.Group_Certificate_Schedule = new HashSet<Group_Certificate_Schedule>();
            this.GroupTrainee_Item = new HashSet<GroupTrainee_Item>();
            this.Instructor_Ability = new HashSet<Instructor_Ability>();
            this.Meeting_Participants = new HashSet<Meeting_Participants>();
            this.Monitor_Ability = new HashSet<Monitor_Ability>();
            this.Notification_Detail = new HashSet<Notification_Detail>();
            this.Orientations = new HashSet<Orientation>();
            this.Payments = new HashSet<Payment>();
            this.PotentialSuccessors_Item = new HashSet<PotentialSuccessors_Item>();
            this.Schedules_destination = new HashSet<Schedules_destination>();
            this.SurveyLMS_Item = new HashSet<SurveyLMS_Item>();
            this.TMS_CertificateApproved = new HashSet<TMS_CertificateApproved>();
            this.TMS_CertificateApproved1 = new HashSet<TMS_CertificateApproved>();
            this.TMS_Course_History_Member = new HashSet<TMS_Course_History_Member>();
            this.TMS_Course_History_Result = new HashSet<TMS_Course_History_Result>();
            this.TMS_Course_Member = new HashSet<TMS_Course_Member>();
            this.TMS_Course_Member_Remark = new HashSet<TMS_Course_Member_Remark>();
            this.Trainee_Contract = new HashSet<Trainee_Contract>();
            this.Trainee_Record = new HashSet<Trainee_Record>();
            this.Trainee_TrainingCenter = new HashSet<Trainee_TrainingCenter>();
            this.Trainee_Type = new HashSet<Trainee_Type>();
            this.TraineeFutures = new HashSet<TraineeFuture>();
            this.TraineeHistories = new HashSet<TraineeHistory>();
            this.Transaction_Course_Trainee = new HashSet<Transaction_Course_Trainee>();
            this.USERs = new HashSet<USER>();
            this.Courses = new HashSet<Course>();
            this.Course_Result_Final_Temp = new HashSet<Course_Result_Final_Temp>();
        }
    
        public int Id { get; set; }
        public Nullable<double> Allowance { get; set; }
        public string PersonalId { get; set; }
        public string str_Staff_Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string str_Email { get; set; }
        public string str_Cell_Phone { get; set; }
        public Nullable<System.DateTime> dtm_Birthdate { get; set; }
        public string str_Station { get; set; }
        public Nullable<bool> bit_Internal { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Job_Title_id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string str_Created_By { get; set; }
        public string str_Deleted_By { get; set; }
        public string str_Last_Modified_By { get; set; }
        public Nullable<System.DateTime> dtm_Created_At { get; set; }
        public Nullable<System.DateTime> dtm_Deleted_At { get; set; }
        public Nullable<System.DateTime> dtm_Last_Modified_At { get; set; }
        public string str_Place_Of_Birth { get; set; }
        public Nullable<System.DateTime> dtm_Join_Date { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Suspended { get; set; }
        public string Passport { get; set; }
        public string Nation { get; set; }
        public string avatar { get; set; }
        public Nullable<int> int_Role { get; set; }
        public Nullable<int> LmsStatus { get; set; }
        public Nullable<System.DateTime> non_working_day { get; set; }
        public Nullable<bool> non_working { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Join_Party_Date { get; set; }
        public Nullable<int> Pay_per_Hour { get; set; }
        public Nullable<int> int_Course_id { get; set; }
        public Nullable<bool> bit_Lms_Available { get; set; }
        public Nullable<bool> IsExaminer { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Attendance> Course_Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Blended_Learning> Course_Blended_Learning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Detail> Course_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Detail_Instructor> Course_Detail_Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Result> Course_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Result_Final> Course_Result_Final { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Result_Summary> Course_Result_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Result_Temp> Course_Result_Temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseRemarkCheckFail> CourseRemarkCheckFails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examiner_Ability> Examiner_Ability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_Certificate_Schedule> Group_Certificate_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTrainee_Item> GroupTrainee_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instructor_Ability> Instructor_Ability { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting_Participants> Meeting_Participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monitor_Ability> Monitor_Ability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification_Detail> Notification_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orientation> Orientations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PotentialSuccessors_Item> PotentialSuccessors_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedules_destination> Schedules_destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyLMS_Item> SurveyLMS_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_CertificateApproved> TMS_CertificateApproved { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_CertificateApproved> TMS_CertificateApproved1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_Course_History_Member> TMS_Course_History_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_Course_History_Result> TMS_Course_History_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_Course_Member> TMS_Course_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_Course_Member_Remark> TMS_Course_Member_Remark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainee_Contract> Trainee_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainee_Record> Trainee_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainee_TrainingCenter> Trainee_TrainingCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainee_Type> Trainee_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraineeFuture> TraineeFutures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraineeHistory> TraineeHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Course_Trainee> Transaction_Course_Trainee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Result_Final_Temp> Course_Result_Final_Temp { get; set; }
    }
}
