//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CAT_CERTIFICATE = new HashSet<CAT_CERTIFICATE>();
            this.CAT_CERTIFICATE1 = new HashSet<CAT_CERTIFICATE>();
            this.CAT_MAIL = new HashSet<CAT_MAIL>();
            this.CAT_MAIL1 = new HashSet<CAT_MAIL>();
            this.Course_Attendance = new HashSet<Course_Attendance>();
            this.Course_Blended_Learning = new HashSet<Course_Blended_Learning>();
            this.Course_Blended_Learning1 = new HashSet<Course_Blended_Learning>();
            this.GroupUserAccesses = new HashSet<GroupUserAccess>();
            this.Instructor_Ability = new HashSet<Instructor_Ability>();
            this.Notification_Detail = new HashSet<Notification_Detail>();
            this.Orientations = new HashSet<Orientation>();
            this.PotentialSuccessors = new HashSet<PotentialSuccessor>();
            this.PotentialSuccessors1 = new HashSet<PotentialSuccessor>();
            this.PotentialSuccessors_Item = new HashSet<PotentialSuccessors_Item>();
            this.PotentialSuccessors_Item1 = new HashSet<PotentialSuccessors_Item>();
            this.PROCESS_Approver = new HashSet<PROCESS_Approver>();
            this.Schedules_destination = new HashSet<Schedules_destination>();
            this.SYS_LogEvent = new HashSet<SYS_LogEvent>();
            this.TMS_Approve_Department = new HashSet<TMS_Approve_Department>();
            this.TMS_APPROVES = new HashSet<TMS_APPROVES>();
            this.TMS_APPROVES1 = new HashSet<TMS_APPROVES>();
            this.TMS_CertificateApproved = new HashSet<TMS_CertificateApproved>();
            this.TMS_CertificateApproved1 = new HashSet<TMS_CertificateApproved>();
            this.USER_HIS = new HashSet<USER_HIS>();
            this.UserPermissions = new HashSet<UserPermission>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ISACTIVE { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ADDRESS { get; set; }
        public string PHONENO { get; set; }
        public string COMPANY { get; set; }
        public string LANGUAGEABBREVIATION { get; set; }
        public Nullable<int> USERSTATE { get; set; }
        public Nullable<System.DateTime> ONLINEAT { get; set; }
        public Nullable<System.DateTime> LASTONLINEAT { get; set; }
        public string TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<bool> STATE_SORTW { get; set; }
        public Nullable<int> GroupUserId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> InstructorId { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Attempts { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> LASTLOGINFAIL { get; set; }
        public string CAT_ALL { get; set; }
        public string SUP_ALL { get; set; }
        public string TRANS_ALL { get; set; }
        public string CUS_ALL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_CERTIFICATE> CAT_CERTIFICATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_CERTIFICATE> CAT_CERTIFICATE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_MAIL> CAT_MAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_MAIL> CAT_MAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Attendance> Course_Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Blended_Learning> Course_Blended_Learning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Blended_Learning> Course_Blended_Learning1 { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupUserAccess> GroupUserAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instructor_Ability> Instructor_Ability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification_Detail> Notification_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orientation> Orientations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PotentialSuccessor> PotentialSuccessors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PotentialSuccessor> PotentialSuccessors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PotentialSuccessors_Item> PotentialSuccessors_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PotentialSuccessors_Item> PotentialSuccessors_Item1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCESS_Approver> PROCESS_Approver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedules_destination> Schedules_destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_LogEvent> SYS_LogEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_Approve_Department> TMS_Approve_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_APPROVES> TMS_APPROVES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_APPROVES> TMS_APPROVES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_CertificateApproved> TMS_CertificateApproved { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_CertificateApproved> TMS_CertificateApproved1 { get; set; }
        public virtual Trainee Trainee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_HIS> USER_HIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
