//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_HIS
    {
        public long ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> LAST_ACTIVE { get; set; }
        public string REQUEST { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
