//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfile()
        {
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string str_File_No { get; set; }
        public string str_Fullname { get; set; }
        public string str_Email { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<System.DateTime> dtm_Created_At { get; set; }
        public string str_Created_By { get; set; }
        public Nullable<System.DateTime> dtm_Modified_At { get; set; }
        public string str_Modified_By { get; set; }
        public Nullable<int> int_Group_Roles_Id { get; set; }
        public Nullable<bool> bit_Deleted { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Group_Roles Group_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
